"""
Documentation artifact tests (AC-D1-1..2, AC-D2-1..2, AC-D4-1..3).

These tests validate the D-artifacts already committed to docs/ without
running any network calls or external tools.

Coverage:
  AC-D1-1  context.mmd starts with C4Context and is a syntactically parseable diagram
  AC-D1-2  container.mmd contains all v0.1 container identifiers
  AC-D2-1  schema.mmd generated by make er, contains erDiagram
  AC-D2-2  schema.mmd contains all expected column names
  AC-D4-1  openapi.json is valid OpenAPI 3.1
  AC-D4-2  openapi.json exists and was generated (not hand-written)
  AC-D4-3  all 4 v0.1 endpoints present in openapi.json paths

mmdc (Mermaid CLI) rendering check: deferred — mmdc not installed in this sandbox.
Architect/tech-writer sign-off (AC-D1-3, AC-D2-3): MANUAL gates recorded below.

Test IDs: T-DOCS-001 .. T-DOCS-015
"""

from __future__ import annotations

import json
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DOCS = _REPO_ROOT / "docs"


# ── AC-D1-1: context.mmd is valid C4Context ───────────────────────────────────


class TestContextDiagram:
    """T-DOCS-001, T-DOCS-002 — AC-D1-1"""

    def test_context_mmd_exists(self) -> None:
        """T-DOCS-001: docs/architecture/context.mmd must exist."""
        p = _DOCS / "architecture" / "context.mmd"
        assert p.exists(), "docs/architecture/context.mmd must exist (D1)"

    def test_context_mmd_starts_with_c4context(self) -> None:
        """T-DOCS-002: AC-D1-1 — context.mmd must begin with C4Context keyword."""
        p = _DOCS / "architecture" / "context.mmd"
        text = p.read_text(encoding="utf-8").strip()
        assert text.startswith("C4Context"), (
            f"context.mmd must start with 'C4Context'; " f"starts with: {text[:50]!r}"
        )

    def test_context_mmd_mentions_synapse_system(self) -> None:
        """T-DOCS-003: context.mmd must reference the Synapse system."""
        p = _DOCS / "architecture" / "context.mmd"
        text = p.read_text(encoding="utf-8")
        assert (
            "synapse" in text.lower() or "Synapse" in text
        ), "context.mmd must mention 'Synapse' (the system being documented)"

    def test_context_mmd_mentions_external_systems(self) -> None:
        """T-DOCS-004: context.mmd must mention Qdrant, bge-m3, and vault filesystem."""
        p = _DOCS / "architecture" / "context.mmd"
        text = p.read_text(encoding="utf-8").lower()
        for ext in ("qdrant", "bge-m3", "vault"):
            assert ext in text, f"context.mmd must mention external system '{ext}' (AC-D1-1)"


# ── AC-D1-2: container.mmd has all v0.1 containers ───────────────────────────


class TestContainerDiagram:
    """T-DOCS-005, T-DOCS-006 — AC-D1-2"""

    def test_container_mmd_exists(self) -> None:
        """T-DOCS-005: docs/architecture/container.mmd must exist."""
        p = _DOCS / "architecture" / "container.mmd"
        assert p.exists(), "docs/architecture/container.mmd must exist (D1)"

    def test_container_mmd_starts_with_c4container(self) -> None:
        """T-DOCS-006: AC-D1-2 — container.mmd must begin with C4Container keyword."""
        p = _DOCS / "architecture" / "container.mmd"
        text = p.read_text(encoding="utf-8").strip()
        assert text.startswith("C4Container"), (
            f"container.mmd must start with 'C4Container'; " f"starts with: {text[:50]!r}"
        )

    def test_container_mmd_mentions_all_v01_containers(self) -> None:
        """T-DOCS-007: AC-D1-2 — all 5 required identifiers must appear in container.mmd."""
        p = _DOCS / "architecture" / "container.mmd"
        text = p.read_text(encoding="utf-8").lower()
        # Required: FastAPI backend, Postgres, Qdrant, bge-m3, vault filesystem
        required = ["fastapi", "postgres", "qdrant", "bge-m3", "vault"]
        for ident in required:
            assert (
                ident in text
            ), f"container.mmd must mention '{ident}' (AC-D1-2 — all v0.1 containers)"

    def test_container_mmd_no_ui_components(self) -> None:
        """T-DOCS-008: container.mmd must not mention UI framework components (deferred to v0.3).

        Note: The word 'react' as a verb (e.g. 'Reacts to events') is allowed.
        We check for 'React 19' or 'sigma.js' or 'CodeMirror' or 'Tauri' — UI frameworks.
        """
        p = _DOCS / "architecture" / "container.mmd"
        text = p.read_text(encoding="utf-8")
        # These are UI framework references (capitalized or with version qualifiers)
        ui_framework_terms = ["sigma.js", "React 19", "CodeMirror", "Tauri"]
        for term in ui_framework_terms:
            assert term not in text, (
                f"container.mmd incorrectly mentions UI framework '{term}' "
                f"(frontend deferred to v0.4)"
            )


# ── AC-D2-1, AC-D2-2: schema.mmd ─────────────────────────────────────────────


class TestERDiagramArtifact:
    """T-DOCS-009..012 — AC-D2-1, AC-D2-2"""

    def test_schema_mmd_exists(self) -> None:
        """T-DOCS-009: AC-D2-1 — docs/er/schema.mmd must exist."""
        p = _DOCS / "er" / "schema.mmd"
        assert p.exists(), "docs/er/schema.mmd must exist (run 'make er')"

    def test_schema_mmd_has_erdiagram(self) -> None:
        """T-DOCS-010: AC-D2-1 — schema.mmd must contain 'erDiagram' keyword."""
        p = _DOCS / "er" / "schema.mmd"
        text = p.read_text(encoding="utf-8")
        assert "erDiagram" in text, "docs/er/schema.mmd must contain 'erDiagram'"

    def test_schema_mmd_has_all_required_columns(self) -> None:
        """T-DOCS-011: AC-D2-2 — schema.mmd must include all AC-PG-3 columns."""
        p = _DOCS / "er" / "schema.mmd"
        text = p.read_text(encoding="utf-8")
        required_columns = [
            "id",
            "vault_id",
            "file_path",
            "title",
            "type",
            "sources",
            "content_hash",
            "source_mtime_ns",  # superset per v0.1-architecture §2.1
            "qdrant_point_id",
            "deleted_at",
            "created_at",
            "updated_at",
            "data_version",  # vault_state column
        ]
        for col in required_columns:
            assert col in text, f"docs/er/schema.mmd must include column '{col}' (AC-D2-2)"

    def test_schema_mmd_has_both_tables(self) -> None:
        """T-DOCS-012: AC-D2-2 — schema.mmd must include PAGES and VAULT_STATE."""
        p = _DOCS / "er" / "schema.mmd"
        text = p.read_text(encoding="utf-8").upper()
        assert "PAGES" in text, "ER diagram must include PAGES table"
        assert "VAULT_STATE" in text, "ER diagram must include VAULT_STATE table"


# ── AC-D4-1..3: openapi.json ─────────────────────────────────────────────────


class TestOpenAPIArtifact:
    """T-DOCS-013..015 — AC-D4-1, AC-D4-2, AC-D4-3"""

    def _load_openapi(self) -> dict:  # type: ignore[type-arg]
        p = _DOCS / "api" / "openapi.json"
        assert p.exists(), "docs/api/openapi.json must exist (run 'make openapi')"
        return json.loads(p.read_text(encoding="utf-8"))  # type: ignore[return-value]

    def test_openapi_json_exists(self) -> None:
        """T-DOCS-013: AC-D4-2 — docs/api/openapi.json must exist."""
        p = _DOCS / "api" / "openapi.json"
        assert p.exists(), "docs/api/openapi.json must exist"

    def test_openapi_json_is_valid_json(self) -> None:
        """T-DOCS-014: AC-D4-1 — openapi.json must be parseable JSON."""
        p = _DOCS / "api" / "openapi.json"
        text = p.read_text(encoding="utf-8")
        data = json.loads(text)
        assert isinstance(data, dict)

    def test_openapi_version_is_3_1(self) -> None:
        """T-DOCS-015: AC-D4-1 — openapi.json version must be 3.1.x."""
        data = self._load_openapi()
        ver = data.get("openapi", "")
        assert ver.startswith("3.1"), f"Expected OpenAPI 3.1.x; got {ver!r}"

    def test_openapi_has_all_four_endpoints(self) -> None:
        """T-DOCS-016: AC-D4-3 — all 4 v0.1 endpoint paths present."""
        data = self._load_openapi()
        paths = data.get("paths", {})
        required = ["/status", "/pages", "/pages/{page_id}", "/ingest/trigger"]
        for rp in required:
            assert rp in paths, f"openapi.json paths missing {rp!r}; found: {list(paths.keys())}"

    def test_openapi_each_endpoint_has_responses(self) -> None:
        """T-DOCS-017: AC-D4-3 — every endpoint must have at least one response defined."""
        data = self._load_openapi()
        for path, ops in data.get("paths", {}).items():
            for method, op in ops.items():
                assert (
                    "responses" in op
                ), f"Endpoint {method.upper()} {path} has no 'responses' defined"

    def test_openapi_info_block_present(self) -> None:
        """T-DOCS-018: openapi.json must have info.title and info.version."""
        data = self._load_openapi()
        assert "info" in data
        assert "title" in data["info"]
        assert "version" in data["info"]

    def test_openapi_ingest_trigger_has_202_response(self) -> None:
        """T-DOCS-019: POST /ingest/trigger must document HTTP 202 response (ADR-0006)."""
        data = self._load_openapi()
        trigger_op = data.get("paths", {}).get("/ingest/trigger", {}).get("post", {})
        responses = trigger_op.get("responses", {})
        assert (
            "202" in responses or 202 in responses
        ), "POST /ingest/trigger must document HTTP 202 response (ADR-0006)"


# ── Manual gate sentinels ─────────────────────────────────────────────────────


class TestManualDocGates:
    """Sentinel tests documenting manual human gates for docs sign-off."""

    def test_ac_d1_3_is_manual_gate(self) -> None:
        """
        T-DOCS-MANUAL-001: AC-D1-3 (architect sign-off on C4 diagrams) is a
        mandatory human gate. This test is a sentinel that passes unconditionally.
        The real gate: solution-architect records approval in the sign-off register
        (EC-9 / EC-13).
        """
        assert True  # MANUAL GATE — GAP-2 / TRACEABILITY.md AC-D1-3

    def test_ac_d2_3_is_manual_gate(self) -> None:
        """
        T-DOCS-MANUAL-002: AC-D2-3 (architect sign-off on ER diagram) is a
        mandatory human gate. This test is a sentinel that passes unconditionally.
        The real gate: solution-architect records approval in the sign-off register
        (EC-10 / EC-13).
        """
        assert True  # MANUAL GATE — GAP-3 / TRACEABILITY.md AC-D2-3

    def test_mmdc_render_check_deferred(self) -> None:
        """
        T-DOCS-MANUAL-003: AC-D1-1/2 render check via 'mmdc -i ... -o /dev/null'
        requires mmdc (Mermaid CLI) to be installed. mmdc is not in this sandbox.

        Deferred to CI stage that has mmdc installed (devops-engineer responsibility).
        Structural content checks (T-DOCS-001..008) are performed instead.
        """
        assert True  # DEFERRED: mmdc not available in sandbox
