"""
K3 — index.md catalogue updater (CLAUDE.md §K3, I1, I5).

`update_index(session, vault_path)` regenerates vault/wiki/index.md as a catalogue of
all live pages grouped by type, with valid YAML frontmatter (I5). The operation is:
  - Idempotent: running it twice with the same page set produces the same file.
  - Incremental-friendly: it is called once per write_wiki_page() call, not per vault event.
    A full vault rescan is never triggered (I1).
  - Obsidian-valid: the frontmatter block (type: index, title, ...) is written first so
    Obsidian recognises the file correctly (I5, K7).

The catalogue groups pages by their page_type column (entity/concept/source/synthesis/
comparison/query). Pages without a type (NULL or empty string) are silently skipped — they
are unresolved ghost rows that should be fixed upstream, not catalogued (ADR-0067 D6 IL-D3).
The `overview`, `index`, and `log` types (auto-generated files) are excluded from the
catalogue to avoid self-referential loops (they are not user-content types per schemas.py).

Duplicate display titles within a type section are collapsed to a single entry; the first
occurrence (by DB query order) wins (ADR-0067 D6 IL-D2/CE-D5).

The index.md file lives at: vault_path/wiki/index.md
"""

from __future__ import annotations

import asyncio
import logging
import os
from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import Page

logger = logging.getLogger(__name__)

# B5 fix: module-level lock so concurrent ingest coroutines never race on the same index.md.
# asyncio.Lock() is acquired per-write; waiting writers serialize behind the first writer.
# No starvation: all callers run in the same event loop.
_INDEX_WRITE_LOCK: asyncio.Lock = asyncio.Lock()

# Ordering for the catalogue sections (consistent output for idempotency checks).
# 'query' is listed after 'comparison' per ADR-0067 D6 (IL-D4).
_TYPE_ORDER: list[str] = ["entity", "concept", "source", "synthesis", "comparison", "query"]

# Types used by auto-generated files — excluded from the user-content catalogue.
# "log" added with D4 (index/log became Page rows) so the log node never renders a
# stray "## Logs — [[…]]" section in index.md (mirrors orchestrator _CATALOGUE_EXCLUDED_TYPES).
_EXCLUDED_TYPES: frozenset[str] = frozenset({"overview", "index", "log"})

_FRONTMATTER_HEADER = """\
---
type: index
title: Synapse Wiki Index
description: Auto-generated catalogue of all wiki pages, grouped by type.
auto_generated: true
---

"""

_PREAMBLE = (
    "> This file is auto-generated by Synapse. Do not edit manually — "
    "it will be overwritten on the next ingest.\n\n"
)


async def update_index(session: AsyncSession, vault_path: Path) -> None:
    """
    Regenerate vault/wiki/index.md as a catalogue of live pages grouped by type (K3, I5).

    Reads live Page rows (deleted_at IS NULL, type not in excluded set, type not NULL/empty)
    from the database via *session*, groups by page_type, deduplicates by case-insensitive
    display title, and writes index.md with valid frontmatter.

    Also renders a bounded "## Recently Updated" section (ADR-0078, llm_wiki §1.8 parity):
    the most-recently-updated live content pages (ORDER BY updated_at DESC), each formatted as
    `- [[<slug>]] — <title>`, capped at 200 and deduped by filename stem. Aggregates
    (index/log/overview) and raw/* paths are excluded. This section appears before the
    per-type catalogue sections.

    Args:
        session:    async SQLAlchemy session (caller owns commit lifecycle).
        vault_path: absolute path to the vault root (index.md lives at wiki/index.md).

    Idempotent: calling twice with the same DB state produces byte-for-byte the same file.
    """
    wiki_dir = vault_path / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)
    index_path = wiki_dir / "index.md"

    # Single query: select (title, page_type, file_path, updated_at, summary) for all live
    # pages. updated_at is used for the "## Recently Updated" section (ADR-0078); summary is
    # the em-dash gloss (K3, 1.9.4 W6, PF-INDEX-GLOSS-1) — NULL for pages written before the
    # backfill or with an empty body.
    # NULL/empty page_type rows are filtered in Python below (the mock bypasses SQL filters).
    # Order by updated_at DESC so recently updated rows come first; the catalogue re-sorts
    # in Python by title within each type section, so DB order doesn't matter for the catalogue.
    result = await session.execute(
        select(Page.title, Page.page_type, Page.file_path, Page.updated_at, Page.summary)
        .where(
            # VAULT-SCOPED (parity fix): count/list ONLY this vault's pages. Without the filter the
            # catalogue counted EVERY vault (e.g. 278 across the DB vs 35) — the cross-vault leak
            # class fixed for the graph resolver.
            Page.vault_id == settings.vault_id,
            Page.deleted_at.is_(None),
        )
        .order_by(Page.updated_at.desc().nullslast(), Page.title.asc().nullslast())
    )
    rows = result.all()

    # Build the "## Recently Updated" list (ADR-0078): live content pages, most-recently-updated
    # first, cap 200, dedup by slug (filename stem), excludes aggregates and raw/* paths.
    recently_updated: list[tuple[str, str, str | None]] = _build_recently_updated(rows)

    # Group by page_type for the catalogue, skipping excluded types and NULL/empty types.
    by_type: dict[str, list[tuple[str, str, str | None]]] = {}

    for title, page_type, file_path, _updated_at, summary in rows:
        # Skip auto-generated catalogue types.
        if page_type in _EXCLUDED_TYPES:
            continue
        # Skip ghost rows with no type — they are unresolved and fixed upstream, not catalogued
        # (ADR-0067 D6 IL-D3). This replaces the old "## Uncategorised" section.
        if not page_type:
            continue
        display_title = title or _stem_from_path(file_path)
        by_type.setdefault(page_type, []).append((display_title, file_path, summary))

    content = _build_index_content(by_type, recently_updated=recently_updated)

    # B5 fix: atomic write (temp file in same dir + os.replace) so readers never see a
    # truncated file, and concurrent rebuilds serialize through _INDEX_WRITE_LOCK so the
    # last *fresh* writer wins instead of the last *stale* writer.
    async with _INDEX_WRITE_LOCK:
        tmp_path = index_path.with_name("index.md.tmp")
        tmp_path.write_text(content, encoding="utf-8")
        os.replace(tmp_path, index_path)  # atomic on POSIX (same directory → same filesystem)
    logger.debug("update_index: wrote %s (%d types)", index_path, len(by_type))


# ── Internal builders ──────────────────────────────────────────────────────────


def _build_recently_updated(
    rows: Sequence[Any],
) -> list[tuple[str, str, str | None]]:
    """
    Build the capped, deduped "## Recently Updated" entry list from DB rows (ADR-0078).

    Rows are expected already ordered by updated_at DESC (the query in update_index orders
    them). Excludes aggregate types (index/log/overview), raw/* file paths, and pages
    with no file_path. Deduplicates by filename stem (slug); first occurrence (most recently
    updated) wins. Returns at most _RECENTLY_UPDATED_CAP entries as (slug, title, summary)
    tuples where title falls back to slug when the DB title is NULL (K3, 1.9.4 W6 gloss).
    """
    seen_slugs: set[str] = set()
    entries: list[tuple[str, str, str | None]] = []
    for title, page_type, file_path, _updated_at, summary in rows:
        if not file_path:
            continue
        # Exclude aggregate auto-generated types.
        if page_type in _EXCLUDED_TYPES:
            continue
        # Exclude raw/* paths (raw source files, not wiki content).
        fp_norm = file_path.replace("\\", "/")
        if fp_norm.startswith("raw/"):
            continue
        slug = Path(file_path).stem
        if not slug:
            continue
        if slug in seen_slugs:
            continue
        seen_slugs.add(slug)
        display = title or slug
        entries.append((slug, display, summary))
        if len(entries) >= _RECENTLY_UPDATED_CAP:
            break
    return entries


def _build_index_content(
    by_type: dict[str, list[tuple[str, str, str | None]]],
    *,
    recently_updated: list[tuple[str, str, str | None]] | None = None,
) -> str:
    """Build the full index.md file content (frontmatter + recently-updated + catalogue).

    Includes a bounded "## Recently Updated" section (ADR-0078) placed BEFORE the
    per-type catalogue sections, matching llm_wiki's prominent placement of this section.
    The section is omitted when the list is empty (empty vault tolerance).

    Deduplicates catalogue entries by case-insensitive display title within each type section
    before rendering (ADR-0067 D6 IL-D2/CE-D5). The total page count reflects
    the deduplicated catalogue set (not the recently-updated count).

    Per-type catalogue entries render an em-dash gloss from ``Page.summary`` when present
    (K3, 1.9.4 W6, PF-INDEX-GLOSS-1): ``- [[Title]] — {summary, truncated}``. Pages with no
    summary yet (NULL — pre-backfill or empty body) render the bare ``- [[Title]]`` line,
    unchanged from before this feature (ADR-0067 D6).
    """
    # Apply dedup per type section (ADR-0067 D6 IL-D2/CE-D5): collapse same-title
    # entries (case-insensitive) to a single line; first occurrence wins.
    by_type_deduped: dict[str, list[tuple[str, str, str | None]]] = {
        pt: _dedup_by_title(pages) for pt, pages in by_type.items()
    }

    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [_FRONTMATTER_HEADER, _PREAMBLE]
    lines.append(f"*Last updated: {now}*\n\n")

    total = sum(len(v) for v in by_type_deduped.values())
    lines.append(f"**Total pages:** {total}\n\n")

    # ── "## Recently Updated" section (ADR-0078, llm_wiki §1.8 parity) ───────────
    # Placed BEFORE the type catalogue — llm_wiki puts this section prominently so
    # readers see recent activity first. Omitted when empty (tolerant of an empty vault).
    # This section already carries an em-dash (slug — title); it is NOT re-glossed with
    # summary here to avoid a double em-dash line (K3 gloss targets the bare catalogue only).
    if recently_updated:
        lines.append("## Recently Updated\n\n")
        for slug, display_title, _summary in recently_updated:
            lines.append(f"- [[{slug}]] — {display_title}\n")
        lines.append("\n")

    # ── Per-type catalogue (K3, ADR-0067 D6, 1.9.4 W6 gloss) ─────────────────────
    # Render known types in canonical order first.
    for page_type in _TYPE_ORDER:
        if page_type not in by_type_deduped:
            continue
        pages = by_type_deduped[page_type]
        heading = _pluralise(page_type)
        lines.append(f"## {heading}\n\n")
        for display_title, _file_path, summary in sorted(pages, key=lambda x: x[0].lower()):
            lines.append(_render_catalogue_line(display_title, summary))
        lines.append("\n")

    # Render any types not in the canonical order (forward-compatible).
    extra_types = sorted(set(by_type_deduped.keys()) - set(_TYPE_ORDER))
    for page_type in extra_types:
        pages = by_type_deduped[page_type]
        lines.append(f"## {_pluralise(page_type)}\n\n")
        for display_title, _file_path, summary in sorted(pages, key=lambda x: x[0].lower()):
            lines.append(_render_catalogue_line(display_title, summary))
        lines.append("\n")

    return "".join(lines)


# Cap for the "## Recently Updated" section (ADR-0078, llm_wiki §1.8 parity).
_RECENTLY_UPDATED_CAP: int = 200

_PLURAL_EXCEPTIONS: dict[str, str] = {
    "entity": "Entities",
    "synthesis": "Synthesis",
    "concept": "Concepts",
    "source": "Sources",
    "comparison": "Comparisons",
    "query": "Queries",  # ADR-0067 D6 (IL-D4): correct plural — 'query' → 'Queries', not 'Querys'
}


def _pluralise(page_type: str) -> str:
    """Return a display-ready plural heading for a page type."""
    lower = page_type.lower()
    if lower in _PLURAL_EXCEPTIONS:
        return _PLURAL_EXCEPTIONS[lower]
    return page_type.capitalize() + "s"


def _dedup_by_title(
    entries: list[tuple[str, str, str | None]],
) -> list[tuple[str, str, str | None]]:
    """
    Deduplicate (display_title, file_path, summary) entries by case-insensitive display title.

    First occurrence wins; insertion order is preserved (ADR-0067 D6 IL-D2/CE-D5).
    This collapses alias entities and other duplicate-title rows to a single catalogue line.
    """
    seen: set[str] = set()
    out: list[tuple[str, str, str | None]] = []
    for display_title, file_path, summary in entries:
        key = display_title.casefold()
        if key not in seen:
            seen.add(key)
            out.append((display_title, file_path, summary))
    return out


# Max chars of Page.summary rendered in the index.md em-dash gloss (K3, 1.9.4 W6).
_GLOSS_MAX_CHARS: int = 120


def _render_catalogue_line(display_title: str, summary: str | None) -> str:
    """
    Render one per-type catalogue line (K3, 1.9.4 W6, PF-INDEX-GLOSS-1).

    With a non-empty summary: ``- [[Title]] — {summary, truncated to _GLOSS_MAX_CHARS}\\n``.
    Without one (NULL/blank — pre-backfill or empty-body page): the bare
    ``- [[Title]]\\n`` line, unchanged from before this feature.
    """
    gloss = (summary or "").strip().replace("\n", " ")
    if not gloss:
        return f"- [[{display_title}]]\n"
    if len(gloss) > _GLOSS_MAX_CHARS:
        gloss = gloss[:_GLOSS_MAX_CHARS].rstrip() + "…"
    return f"- [[{display_title}]] — {gloss}\n"


def _stem_from_path(file_path: str | None) -> str:
    """Return the filename stem as a fallback display title when page.title is NULL."""
    if not file_path:
        return "(untitled)"
    return Path(file_path).stem
