"""
K3 — index.md catalogue updater (CLAUDE.md §K3, I1, I5).

`update_index(session, vault_path)` regenerates vault/wiki/index.md as a catalogue of
all live pages grouped by type, with valid YAML frontmatter (I5). The operation is:
  - Idempotent: running it twice with the same page set produces the same file.
  - Incremental-friendly: it is called once per write_wiki_page() call, not per vault event.
    A full vault rescan is never triggered (I1).
  - Obsidian-valid: the frontmatter block (type: index, title, ...) is written first so
    Obsidian recognises the file correctly (I5, K7).

The catalogue groups pages by their page_type column (entity/concept/source/synthesis/
comparison). Pages without a type go under an "Uncategorised" heading. The `overview` and
`index` types (auto-generated files) are excluded from the catalogue to avoid self-referential
loops (they are not user-content types per schemas.py).

The index.md file lives at: vault_path/wiki/index.md
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Page

logger = logging.getLogger(__name__)

# Ordering for the catalogue sections (consistent output for idempotency checks).
_TYPE_ORDER: list[str] = ["entity", "concept", "source", "synthesis", "comparison"]

# Types used by auto-generated files — excluded from the user-content catalogue.
_EXCLUDED_TYPES: frozenset[str] = frozenset({"overview", "index"})

_FRONTMATTER_HEADER = """\
---
type: index
title: Synapse Wiki Index
description: Auto-generated catalogue of all wiki pages, grouped by type.
auto_generated: true
---

"""

_PREAMBLE = (
    "> This file is auto-generated by Synapse. Do not edit manually — "
    "it will be overwritten on the next ingest.\n\n"
)


async def update_index(session: AsyncSession, vault_path: Path) -> None:
    """
    Regenerate vault/wiki/index.md as a catalogue of live pages grouped by type (K3, I5).

    Reads live Page rows (deleted_at IS NULL, type not in excluded set) from the database
    via *session*, groups by page_type, and writes index.md with valid frontmatter.

    Args:
        session:    async SQLAlchemy session (caller owns commit lifecycle).
        vault_path: absolute path to the vault root (index.md lives at wiki/index.md).

    Idempotent: calling twice with the same DB state produces byte-for-byte the same file.
    """
    wiki_dir = vault_path / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)
    index_path = wiki_dir / "index.md"

    # Query all live, non-excluded pages ordered consistently.
    result = await session.execute(
        select(Page.title, Page.page_type, Page.file_path)
        .where(
            Page.deleted_at.is_(None),
        )
        .order_by(Page.page_type.asc().nullslast(), Page.title.asc().nullslast())
    )
    rows = result.all()

    # Group by page_type, skipping excluded types and pages without a title.
    by_type: dict[str, list[tuple[str, str]]] = {}
    uncategorised: list[tuple[str, str]] = []

    for title, page_type, file_path in rows:
        if page_type in _EXCLUDED_TYPES:
            continue
        display_title = title or _stem_from_path(file_path)
        if page_type and page_type not in _EXCLUDED_TYPES:
            by_type.setdefault(page_type, []).append((display_title, file_path))
        else:
            uncategorised.append((display_title, file_path))

    content = _build_index_content(by_type, uncategorised)

    index_path.write_text(content, encoding="utf-8")
    logger.debug("update_index: wrote %s (%d types)", index_path, len(by_type))


# ── Internal builders ──────────────────────────────────────────────────────────


def _build_index_content(
    by_type: dict[str, list[tuple[str, str]]],
    uncategorised: list[tuple[str, str]],
) -> str:
    """Build the full index.md file content (frontmatter + catalogue sections)."""
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [_FRONTMATTER_HEADER, _PREAMBLE]
    lines.append(f"*Last updated: {now}*\n\n")

    total = sum(len(v) for v in by_type.values()) + len(uncategorised)
    lines.append(f"**Total pages:** {total}\n\n")

    # Render known types in canonical order first.
    for page_type in _TYPE_ORDER:
        if page_type not in by_type:
            continue
        pages = by_type[page_type]
        heading = _pluralise(page_type)
        lines.append(f"## {heading}\n\n")
        for display_title, _file_path in sorted(pages, key=lambda x: x[0].lower()):
            lines.append(f"- [[{display_title}]]\n")
        lines.append("\n")

    # Render any types not in the canonical order (forward-compatible).
    extra_types = sorted(set(by_type.keys()) - set(_TYPE_ORDER))
    for page_type in extra_types:
        pages = by_type[page_type]
        lines.append(f"## {_pluralise(page_type)}\n\n")
        for display_title, _file_path in sorted(pages, key=lambda x: x[0].lower()):
            lines.append(f"- [[{display_title}]]\n")
        lines.append("\n")

    # Uncategorised section.
    if uncategorised:
        lines.append("## Uncategorised\n\n")
        for display_title, _file_path in sorted(uncategorised, key=lambda x: x[0].lower()):
            lines.append(f"- [[{display_title}]]\n")
        lines.append("\n")

    return "".join(lines)


_PLURAL_EXCEPTIONS: dict[str, str] = {
    "entity": "Entities",
    "synthesis": "Synthesis",
    "concept": "Concepts",
    "source": "Sources",
    "comparison": "Comparisons",
}


def _pluralise(page_type: str) -> str:
    """Return a display-ready plural heading for a page type."""
    lower = page_type.lower()
    if lower in _PLURAL_EXCEPTIONS:
        return _PLURAL_EXCEPTIONS[lower]
    return page_type.capitalize() + "s"


def _stem_from_path(file_path: str | None) -> str:
    """Return the filename stem as a fallback display title when page.title is NULL."""
    if not file_path:
        return "(untitled)"
    return Path(file_path).stem
