/**
 * main.tsx — Synapse frontend entry point.
 *
 * React 19 + Vite. Single-page app: one route "/" renders the GraphViewer.
 * No router library needed for v0.3 (single route per ADR-0015 §2).
 */

import React from "react";
import { createRoot } from "react-dom/client";
// i18next must be initialised before the React tree renders (F16 / ADR-0018 §6)
import "./i18n";
import App from "./App";

const rootEl = document.getElementById("root");

if (!rootEl) {
  throw new Error("[Synapse] Root element #root not found. Check index.html.");
}

// React 19 concurrent root
createRoot(rootEl).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);

/**
 * PWA service worker registration (F15 / AC-F15-1).
 *
 * Guards:
 *  - Production builds only (__DEV__ is injected by Vite; false in prod).
 *  - serviceWorker must be supported by the browser.
 *  - import.meta.env.MODE !== 'test' prevents registration during vitest
 *    (vitest sets MODE='test' when it runs under jsdom).
 *
 * The SW (dist/sw.js, generated by vite-plugin-pwa / Workbox) handles:
 *  - Precache of the static shell (JS/CSS/HTML/icons).
 *  - NetworkOnly for all API paths (I1 dataVersion invariant — no stale data).
 *  - NavigateFallback to index.html for offline shell support.
 */
if (
  !__DEV__ &&
  import.meta.env.MODE !== "test" &&
  "serviceWorker" in navigator
) {
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .then((_registration) => {
        // SW registered successfully — no action needed, Workbox handles updates.
      })
      .catch((err: unknown) => {
        console.warn("[Synapse] Service worker registration failed:", err);
      });
  });
}
